/*
 * SPDX-License-Identifier: (Apache-2.0 OR LGPL-2.1-or-later)
 *
 * Copyright 2022 Sony Semiconductor Solutions Corporation
 */

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/time.h>

#include "gtest/gtest.h"

#include <Arduino.h>

#include <OutputMixer.h>

#include "SFZSink.h"

void create_file(const String &file_path, const String &text) {
    registerDummyFile(file_path, text);
}

class SfzTest : public ::testing::Test {
public:
    int getSfzDataNum(const SFZSink &sfz_test) {
        return sfz_test.regions_.size();
    }
    int getSfzDataSwlokey(const SFZSink &sfz_test) {
        return sfz_test.sw_lokey_;
    }
    int getSfzDataSwhikey(const SFZSink &sfz_test) {
        return sfz_test.sw_hikey_;
    }
    int getSfzDataSwkey(const SFZSink &sfz_test) {
        return sfz_test.sw_last_;
    }
    std::vector<SFZSink::Region> getSfzData(const SFZSink &sfz_test) {
        return sfz_test.regions_;
    }

protected:
    std::vector<SFZSink::Region> regions;
};

TEST_F(SfzTest, lokey_notename) {
    create_file("testdata/SFZSink/lokey_notename.sfz",
                "<region> lokey=Cb8\n"
                "<region> lokey=C-1\n"
                "<region> lokey=C8\n"
                "<region> lokey=C#0\n"
                "<region> lokey=C#3\n"
                "<region> lokey=Db3\n"
                "<region> lokey=Db9\n"
                "<region> lokey=D-1\n"
                "<region> lokey=D8\n"
                "<region> lokey=D#0\n"
                "<region> lokey=Eb3\n"
                "<region> lokey=Eb8\n"
                "<region> lokey=E-1\n"
                "<region> lokey=E#0\n"
                "<region> lokey=E#9\n"
                "<region> lokey=Fb0\n"
                "<region> lokey=Fb3\n"
                "<region> lokey=F8\n"
                "<region> lokey=F#-1\n"
                "<region> lokey=F#9\n"
                "<region> lokey=Gb8\n"
                "<region> lokey=Gb9\n"
                "<region> lokey=G-1\n"
                "<region> lokey=G0\n"
                "<region> lokey=G#3\n"
                "<region> lokey=Ab0\n"
                "<region> lokey=A3\n"
                "<region> lokey=A#-1\n"
                "<region> lokey=A#7\n"
                "<region> lokey=A#8\n"
                "<region> lokey=Bb-1\n"
                "<region> lokey=Bb0\n"
                "<region> lokey=B3\n"
                "<region> lokey=B8\n"
                "<region> lokey=B#7\n"
                "<region> lokey=cb-1\n"
                "<region> lokey=cb3\n"
                "<region> lokey=cb7\n"
                "<region> lokey=c9\n"
                "<region> lokey=c#0\n"
                "<region> lokey=db3\n"
                "<region> lokey=d-1\n"
                "<region> lokey=d0\n"
                "<region> lokey=d#8\n"
                "<region> lokey=d#9\n"
                "<region> lokey=eb8\n"
                "<region> lokey=e0\n"
                "<region> lokey=e#-1\n"
                "<region> lokey=e#3\n"
                "<region> lokey=e#9\n"
                "<region> lokey=fb-1\n"
                "<region> lokey=f3\n"
                "<region> lokey=f#0\n"
                "<region> lokey=f#8\n"
                "<region> lokey=f#9\n"
                "<region> lokey=g9\n"
                "<region> lokey=g#-1\n"
                "<region> lokey=g#3\n"
                "<region> lokey=g#7\n"
                "<region> lokey=gb0\n"
                "<region> lokey=ab7\n"
                "<region> lokey=ab8\n"
                "<region> lokey=a3\n"
                "<region> lokey=a#-1\n"
                "<region> lokey=a#0\n"
                "<region> lokey=bb0\n"
                "<region> lokey=bb8\n"
                "<region> lokey=b-1\n"
                "<region> lokey=b7\n"
                "<region> lokey=b#3\n"
                "<region> lokey=C##\n"
                "<region> lokey=C#-2\n"
                "<region> lokey=C#b\n"
                "<region> lokey=C-100\n"
                "<region> lokey=C10\n"
                "<region> lokey=CbZZ\n"
                "<region> lokey=D#\n"
                "<region> lokey=D#-100\n"
                "<region> lokey=D#10\n"
                "<region> lokey=D#ZZ\n"
                "<region> lokey=Db\n"
                "<region> lokey=Db-2\n"
                "<region> lokey=E#-100\n"
                "<region> lokey=E#ZZ\n"
                "<region> lokey=E#b\n"
                "<region> lokey=E-2\n"
                "<region> lokey=E10\n"
                "<region> lokey=Eb#\n"
                "<region> lokey=F##\n"
                "<region> lokey=F#-100\n"
                "<region> lokey=F#-2\n"
                "<region> lokey=FZZ\n"
                "<region> lokey=Fb10\n"
                "<region> lokey=Fbb\n"
                "<region> lokey=G##\n"
                "<region> lokey=G#-100\n"
                "<region> lokey=G#ZZ\n"
                "<region> lokey=G10\n"
                "<region> lokey=Gb\n"
                "<region> lokey=Gb-2\n"
                "<region> lokey=A#\n"
                "<region> lokey=A#10\n"
                "<region> lokey=AZZ\n"
                "<region> lokey=Ab\n"
                "<region> lokey=Ab-100\n"
                "<region> lokey=Ab-2\n"
                "<region> lokey=B#\n"
                "<region> lokey=B#-2\n"
                "<region> lokey=B-100\n"
                "<region> lokey=Bb\n"
                "<region> lokey=Bb10\n"
                "<region> lokey=BbZZ\n"
                "<region> lokey=c#\n"
                "<region> lokey=c#10\n"
                "<region> lokey=c#b\n"
                "<region> lokey=c-2\n"
                "<region> lokey=cb-100\n"
                "<region> lokey=cbZZ\n"
                "<region> lokey=d##\n"
                "<region> lokey=d-100\n"
                "<region> lokey=d-2\n"
                "<region> lokey=d10\n"
                "<region> lokey=dbZZ\n"
                "<region> lokey=dbb\n"
                "<region> lokey=e#\n"
                "<region> lokey=e#-2\n"
                "<region> lokey=e#10\n"
                "<region> lokey=eZZ\n"
                "<region> lokey=eb\n"
                "<region> lokey=eb-100\n"
                "<region> lokey=f#\n"
                "<region> lokey=f#ZZ\n"
                "<region> lokey=f-100\n"
                "<region> lokey=fb-2\n"
                "<region> lokey=fb10\n"
                "<region> lokey=fbb\n"
                "<region> lokey=g#ZZ\n"
                "<region> lokey=g10\n"
                "<region> lokey=gb\n"
                "<region> lokey=gb#\n"
                "<region> lokey=gb-100\n"
                "<region> lokey=gb-2\n"
                "<region> lokey=a#ZZ\n"
                "<region> lokey=a-2\n"
                "<region> lokey=a10\n"
                "<region> lokey=ab#\n"
                "<region> lokey=ab-100\n"
                "<region> lokey=abb\n"
                "<region> lokey=b#-2\n"
                "<region> lokey=b#ZZ\n"
                "<region> lokey=b10\n"
                "<region> lokey=bb#\n"
                "<region> lokey=bb-100\n"
                "<region> lokey=bbb\n"
                "<region> lokey=Z3\n"
                "<region> lokey=Zb3\n"
                "<region> lokey=Z#3\n"
                "<region> lokey=10#3\n"
                "<region> lokey=10b3\n"
                "<region> lokey==C3\n"
                "<region> lokey=Cz3\n"
                "<region> lokey=C♭3\n"
                "<region> lokey=C=3\n"
                "");
    SFZSink sfz_test = SFZSink("testdata/SFZSink/lokey_notename.sfz");
    regions = getSfzData(sfz_test);

    EXPECT_EQ(regions.size(), 163);
    if (regions.size() >= 163) {
        const uint32_t default_lokey = NOTE_NUMBER_MIN;
        EXPECT_EQ(regions[0].lokey, 107);
        EXPECT_EQ(regions[1].lokey, 0);
        EXPECT_EQ(regions[2].lokey, 108);
        EXPECT_EQ(regions[3].lokey, 13);
        EXPECT_EQ(regions[4].lokey, 49);
        EXPECT_EQ(regions[5].lokey, 49);
        EXPECT_EQ(regions[6].lokey, 121);
        EXPECT_EQ(regions[7].lokey, 2);
        EXPECT_EQ(regions[8].lokey, 110);
        EXPECT_EQ(regions[9].lokey, 15);
        EXPECT_EQ(regions[10].lokey, 51);
        EXPECT_EQ(regions[11].lokey, 111);
        EXPECT_EQ(regions[12].lokey, 4);
        EXPECT_EQ(regions[13].lokey, 17);
        EXPECT_EQ(regions[14].lokey, 125);
        EXPECT_EQ(regions[15].lokey, 16);
        EXPECT_EQ(regions[16].lokey, 52);
        EXPECT_EQ(regions[17].lokey, 113);
        EXPECT_EQ(regions[18].lokey, 6);
        EXPECT_EQ(regions[19].lokey, 126);
        EXPECT_EQ(regions[20].lokey, 114);
        EXPECT_EQ(regions[21].lokey, 126);
        EXPECT_EQ(regions[22].lokey, 7);
        EXPECT_EQ(regions[23].lokey, 19);
        EXPECT_EQ(regions[24].lokey, 56);
        EXPECT_EQ(regions[25].lokey, 20);
        EXPECT_EQ(regions[26].lokey, 57);
        EXPECT_EQ(regions[27].lokey, 10);
        EXPECT_EQ(regions[28].lokey, 106);
        EXPECT_EQ(regions[29].lokey, 118);
        EXPECT_EQ(regions[30].lokey, 10);
        EXPECT_EQ(regions[31].lokey, 22);
        EXPECT_EQ(regions[32].lokey, 59);
        EXPECT_EQ(regions[33].lokey, 119);
        EXPECT_EQ(regions[34].lokey, 108);
        EXPECT_EQ(regions[35].lokey, default_lokey);
        EXPECT_EQ(regions[36].lokey, 47);
        EXPECT_EQ(regions[37].lokey, 95);
        EXPECT_EQ(regions[38].lokey, 120);
        EXPECT_EQ(regions[39].lokey, 13);
        EXPECT_EQ(regions[40].lokey, 49);
        EXPECT_EQ(regions[41].lokey, 2);
        EXPECT_EQ(regions[42].lokey, 14);
        EXPECT_EQ(regions[43].lokey, 111);
        EXPECT_EQ(regions[44].lokey, 123);
        EXPECT_EQ(regions[45].lokey, 111);
        EXPECT_EQ(regions[46].lokey, 16);
        EXPECT_EQ(regions[47].lokey, 5);
        EXPECT_EQ(regions[48].lokey, 53);
        EXPECT_EQ(regions[49].lokey, 125);
        EXPECT_EQ(regions[50].lokey, 4);
        EXPECT_EQ(regions[51].lokey, 53);
        EXPECT_EQ(regions[52].lokey, 18);
        EXPECT_EQ(regions[53].lokey, 114);
        EXPECT_EQ(regions[54].lokey, 126);
        EXPECT_EQ(regions[55].lokey, 127);
        EXPECT_EQ(regions[56].lokey, 8);
        EXPECT_EQ(regions[57].lokey, 56);
        EXPECT_EQ(regions[58].lokey, 104);
        EXPECT_EQ(regions[59].lokey, 18);
        EXPECT_EQ(regions[60].lokey, 104);
        EXPECT_EQ(regions[61].lokey, 116);
        EXPECT_EQ(regions[62].lokey, 57);
        EXPECT_EQ(regions[63].lokey, 10);
        EXPECT_EQ(regions[64].lokey, 22);
        EXPECT_EQ(regions[65].lokey, 22);
        EXPECT_EQ(regions[66].lokey, 118);
        EXPECT_EQ(regions[67].lokey, 11);
        EXPECT_EQ(regions[68].lokey, 107);
        EXPECT_EQ(regions[69].lokey, 60);
        EXPECT_EQ(regions[70].lokey, default_lokey);
        EXPECT_EQ(regions[71].lokey, default_lokey);
        EXPECT_EQ(regions[72].lokey, default_lokey);
        EXPECT_EQ(regions[73].lokey, default_lokey);
        EXPECT_EQ(regions[74].lokey, default_lokey);
        EXPECT_EQ(regions[75].lokey, default_lokey);
        EXPECT_EQ(regions[76].lokey, default_lokey);
        EXPECT_EQ(regions[77].lokey, default_lokey);
        EXPECT_EQ(regions[78].lokey, default_lokey);
        EXPECT_EQ(regions[79].lokey, default_lokey);
        EXPECT_EQ(regions[80].lokey, default_lokey);
        EXPECT_EQ(regions[81].lokey, default_lokey);
        EXPECT_EQ(regions[82].lokey, default_lokey);
        EXPECT_EQ(regions[83].lokey, default_lokey);
        EXPECT_EQ(regions[84].lokey, default_lokey);
        EXPECT_EQ(regions[85].lokey, default_lokey);
        EXPECT_EQ(regions[86].lokey, default_lokey);
        EXPECT_EQ(regions[87].lokey, default_lokey);
        EXPECT_EQ(regions[88].lokey, default_lokey);
        EXPECT_EQ(regions[89].lokey, default_lokey);
        EXPECT_EQ(regions[90].lokey, default_lokey);
        EXPECT_EQ(regions[91].lokey, default_lokey);
        EXPECT_EQ(regions[92].lokey, default_lokey);
        EXPECT_EQ(regions[93].lokey, default_lokey);
        EXPECT_EQ(regions[94].lokey, default_lokey);
        EXPECT_EQ(regions[95].lokey, default_lokey);
        EXPECT_EQ(regions[96].lokey, default_lokey);
        EXPECT_EQ(regions[97].lokey, default_lokey);
        EXPECT_EQ(regions[98].lokey, default_lokey);
        EXPECT_EQ(regions[99].lokey, default_lokey);
        EXPECT_EQ(regions[100].lokey, default_lokey);
        EXPECT_EQ(regions[101].lokey, default_lokey);
        EXPECT_EQ(regions[102].lokey, default_lokey);
        EXPECT_EQ(regions[103].lokey, default_lokey);
        EXPECT_EQ(regions[104].lokey, default_lokey);
        EXPECT_EQ(regions[105].lokey, default_lokey);
        EXPECT_EQ(regions[106].lokey, default_lokey);
        EXPECT_EQ(regions[107].lokey, default_lokey);
        EXPECT_EQ(regions[108].lokey, default_lokey);
        EXPECT_EQ(regions[109].lokey, default_lokey);
        EXPECT_EQ(regions[110].lokey, default_lokey);
        EXPECT_EQ(regions[111].lokey, default_lokey);
        EXPECT_EQ(regions[112].lokey, default_lokey);
        EXPECT_EQ(regions[113].lokey, default_lokey);
        EXPECT_EQ(regions[114].lokey, default_lokey);
        EXPECT_EQ(regions[115].lokey, default_lokey);
        EXPECT_EQ(regions[116].lokey, default_lokey);
        EXPECT_EQ(regions[117].lokey, default_lokey);
        EXPECT_EQ(regions[118].lokey, default_lokey);
        EXPECT_EQ(regions[119].lokey, default_lokey);
        EXPECT_EQ(regions[120].lokey, default_lokey);
        EXPECT_EQ(regions[121].lokey, default_lokey);
        EXPECT_EQ(regions[122].lokey, default_lokey);
        EXPECT_EQ(regions[123].lokey, default_lokey);
        EXPECT_EQ(regions[124].lokey, default_lokey);
        EXPECT_EQ(regions[125].lokey, default_lokey);
        EXPECT_EQ(regions[126].lokey, default_lokey);
        EXPECT_EQ(regions[127].lokey, default_lokey);
        EXPECT_EQ(regions[128].lokey, default_lokey);
        EXPECT_EQ(regions[129].lokey, default_lokey);
        EXPECT_EQ(regions[130].lokey, default_lokey);
        EXPECT_EQ(regions[131].lokey, default_lokey);
        EXPECT_EQ(regions[132].lokey, default_lokey);
        EXPECT_EQ(regions[133].lokey, default_lokey);
        EXPECT_EQ(regions[134].lokey, default_lokey);
        EXPECT_EQ(regions[135].lokey, default_lokey);
        EXPECT_EQ(regions[136].lokey, default_lokey);
        EXPECT_EQ(regions[137].lokey, default_lokey);
        EXPECT_EQ(regions[138].lokey, default_lokey);
        EXPECT_EQ(regions[139].lokey, default_lokey);
        EXPECT_EQ(regions[140].lokey, default_lokey);
        EXPECT_EQ(regions[141].lokey, default_lokey);
        EXPECT_EQ(regions[142].lokey, default_lokey);
        EXPECT_EQ(regions[143].lokey, default_lokey);
        EXPECT_EQ(regions[144].lokey, default_lokey);
        EXPECT_EQ(regions[145].lokey, default_lokey);
        EXPECT_EQ(regions[146].lokey, default_lokey);
        EXPECT_EQ(regions[147].lokey, default_lokey);
        EXPECT_EQ(regions[148].lokey, default_lokey);
        EXPECT_EQ(regions[149].lokey, default_lokey);
        EXPECT_EQ(regions[150].lokey, default_lokey);
        EXPECT_EQ(regions[151].lokey, default_lokey);
        EXPECT_EQ(regions[152].lokey, default_lokey);
        EXPECT_EQ(regions[153].lokey, default_lokey);
        EXPECT_EQ(regions[154].lokey, default_lokey);
        EXPECT_EQ(regions[155].lokey, default_lokey);
        EXPECT_EQ(regions[156].lokey, default_lokey);
        EXPECT_EQ(regions[157].lokey, default_lokey);
        EXPECT_EQ(regions[158].lokey, default_lokey);
        EXPECT_EQ(regions[159].lokey, default_lokey);
        EXPECT_EQ(regions[160].lokey, default_lokey);
        EXPECT_EQ(regions[161].lokey, default_lokey);
        EXPECT_EQ(regions[162].lokey, default_lokey);
    }
}

TEST_F(SfzTest, hikey_notename) {
    create_file("testdata/SFZSink/hikey_notename.sfz",
                "<region> hikey=Cb8\n"
                "<region> hikey=C-1\n"
                "<region> hikey=C8\n"
                "<region> hikey=C#0\n"
                "<region> hikey=C#3\n"
                "<region> hikey=Db3\n"
                "<region> hikey=Db9\n"
                "<region> hikey=D-1\n"
                "<region> hikey=D8\n"
                "<region> hikey=D#0\n"
                "<region> hikey=Eb3\n"
                "<region> hikey=Eb8\n"
                "<region> hikey=E-1\n"
                "<region> hikey=E#0\n"
                "<region> hikey=E#9\n"
                "<region> hikey=Fb0\n"
                "<region> hikey=Fb3\n"
                "<region> hikey=F8\n"
                "<region> hikey=F#-1\n"
                "<region> hikey=F#9\n"
                "<region> hikey=Gb8\n"
                "<region> hikey=Gb9\n"
                "<region> hikey=G-1\n"
                "<region> hikey=G0\n"
                "<region> hikey=G#3\n"
                "<region> hikey=Ab0\n"
                "<region> hikey=A3\n"
                "<region> hikey=A#-1\n"
                "<region> hikey=A#7\n"
                "<region> hikey=A#8\n"
                "<region> hikey=Bb-1\n"
                "<region> hikey=Bb0\n"
                "<region> hikey=B3\n"
                "<region> hikey=B8\n"
                "<region> hikey=B#7\n"
                "<region> hikey=cb-1\n"
                "<region> hikey=cb3\n"
                "<region> hikey=cb7\n"
                "<region> hikey=c9\n"
                "<region> hikey=c#0\n"
                "<region> hikey=db3\n"
                "<region> hikey=d-1\n"
                "<region> hikey=d0\n"
                "<region> hikey=d#8\n"
                "<region> hikey=d#9\n"
                "<region> hikey=eb8\n"
                "<region> hikey=e0\n"
                "<region> hikey=e#-1\n"
                "<region> hikey=e#3\n"
                "<region> hikey=e#9\n"
                "<region> hikey=fb-1\n"
                "<region> hikey=f3\n"
                "<region> hikey=f#0\n"
                "<region> hikey=f#8\n"
                "<region> hikey=f#9\n"
                "<region> hikey=g9\n"
                "<region> hikey=g#-1\n"
                "<region> hikey=g#3\n"
                "<region> hikey=g#7\n"
                "<region> hikey=gb0\n"
                "<region> hikey=ab7\n"
                "<region> hikey=ab8\n"
                "<region> hikey=a3\n"
                "<region> hikey=a#-1\n"
                "<region> hikey=a#0\n"
                "<region> hikey=bb0\n"
                "<region> hikey=bb8\n"
                "<region> hikey=b-1\n"
                "<region> hikey=b7\n"
                "<region> hikey=b#3\n"
                "<region> hikey=C##\n"
                "<region> hikey=C#-2\n"
                "<region> hikey=C#b\n"
                "<region> hikey=C-100\n"
                "<region> hikey=C10\n"
                "<region> hikey=CbZZ\n"
                "<region> hikey=D#\n"
                "<region> hikey=D#-100\n"
                "<region> hikey=D#10\n"
                "<region> hikey=D#ZZ\n"
                "<region> hikey=Db\n"
                "<region> hikey=Db-2\n"
                "<region> hikey=E#-100\n"
                "<region> hikey=E#ZZ\n"
                "<region> hikey=E#b\n"
                "<region> hikey=E-2\n"
                "<region> hikey=E10\n"
                "<region> hikey=Eb#\n"
                "<region> hikey=F##\n"
                "<region> hikey=F#-100\n"
                "<region> hikey=F#-2\n"
                "<region> hikey=FZZ\n"
                "<region> hikey=Fb10\n"
                "<region> hikey=Fbb\n"
                "<region> hikey=G##\n"
                "<region> hikey=G#-100\n"
                "<region> hikey=G#ZZ\n"
                "<region> hikey=G10\n"
                "<region> hikey=Gb\n"
                "<region> hikey=Gb-2\n"
                "<region> hikey=A#\n"
                "<region> hikey=A#10\n"
                "<region> hikey=AZZ\n"
                "<region> hikey=Ab\n"
                "<region> hikey=Ab-100\n"
                "<region> hikey=Ab-2\n"
                "<region> hikey=B#\n"
                "<region> hikey=B#-2\n"
                "<region> hikey=B-100\n"
                "<region> hikey=Bb\n"
                "<region> hikey=Bb10\n"
                "<region> hikey=BbZZ\n"
                "<region> hikey=c#\n"
                "<region> hikey=c#10\n"
                "<region> hikey=c#b\n"
                "<region> hikey=c-2\n"
                "<region> hikey=cb-100\n"
                "<region> hikey=cbZZ\n"
                "<region> hikey=d##\n"
                "<region> hikey=d-100\n"
                "<region> hikey=d-2\n"
                "<region> hikey=d10\n"
                "<region> hikey=dbZZ\n"
                "<region> hikey=dbb\n"
                "<region> hikey=e#\n"
                "<region> hikey=e#-2\n"
                "<region> hikey=e#10\n"
                "<region> hikey=eZZ\n"
                "<region> hikey=eb\n"
                "<region> hikey=eb-100\n"
                "<region> hikey=f#\n"
                "<region> hikey=f#ZZ\n"
                "<region> hikey=f-100\n"
                "<region> hikey=fb-2\n"
                "<region> hikey=fb10\n"
                "<region> hikey=fbb\n"
                "<region> hikey=g#ZZ\n"
                "<region> hikey=g10\n"
                "<region> hikey=gb\n"
                "<region> hikey=gb#\n"
                "<region> hikey=gb-100\n"
                "<region> hikey=gb-2\n"
                "<region> hikey=a#ZZ\n"
                "<region> hikey=a-2\n"
                "<region> hikey=a10\n"
                "<region> hikey=ab#\n"
                "<region> hikey=ab-100\n"
                "<region> hikey=abb\n"
                "<region> hikey=b#-2\n"
                "<region> hikey=b#ZZ\n"
                "<region> hikey=b10\n"
                "<region> hikey=bb#\n"
                "<region> hikey=bb-100\n"
                "<region> hikey=bbb\n"
                "<region> hikey=Z3\n"
                "<region> hikey=Zb3\n"
                "<region> hikey=Z#3\n"
                "<region> hikey=10#3\n"
                "<region> hikey=10b3\n"
                "<region> hikey==C3\n"
                "<region> hikey=Cz3\n"
                "<region> hikey=C♭3\n"
                "<region> hikey=C=3\n"
                "");
    SFZSink sfz_test = SFZSink("testdata/SFZSink/hikey_notename.sfz");
    regions = getSfzData(sfz_test);

    EXPECT_EQ(regions.size(), 163);
    if (regions.size() >= 163) {
        const uint32_t default_hikey = NOTE_NUMBER_MAX;
        EXPECT_EQ(regions[0].hikey, 107);
        EXPECT_EQ(regions[1].hikey, 0);
        EXPECT_EQ(regions[2].hikey, 108);
        EXPECT_EQ(regions[3].hikey, 13);
        EXPECT_EQ(regions[4].hikey, 49);
        EXPECT_EQ(regions[5].hikey, 49);
        EXPECT_EQ(regions[6].hikey, 121);
        EXPECT_EQ(regions[7].hikey, 2);
        EXPECT_EQ(regions[8].hikey, 110);
        EXPECT_EQ(regions[9].hikey, 15);
        EXPECT_EQ(regions[10].hikey, 51);
        EXPECT_EQ(regions[11].hikey, 111);
        EXPECT_EQ(regions[12].hikey, 4);
        EXPECT_EQ(regions[13].hikey, 17);
        EXPECT_EQ(regions[14].hikey, 125);
        EXPECT_EQ(regions[15].hikey, 16);
        EXPECT_EQ(regions[16].hikey, 52);
        EXPECT_EQ(regions[17].hikey, 113);
        EXPECT_EQ(regions[18].hikey, 6);
        EXPECT_EQ(regions[19].hikey, 126);
        EXPECT_EQ(regions[20].hikey, 114);
        EXPECT_EQ(regions[21].hikey, 126);
        EXPECT_EQ(regions[22].hikey, 7);
        EXPECT_EQ(regions[23].hikey, 19);
        EXPECT_EQ(regions[24].hikey, 56);
        EXPECT_EQ(regions[25].hikey, 20);
        EXPECT_EQ(regions[26].hikey, 57);
        EXPECT_EQ(regions[27].hikey, 10);
        EXPECT_EQ(regions[28].hikey, 106);
        EXPECT_EQ(regions[29].hikey, 118);
        EXPECT_EQ(regions[30].hikey, 10);
        EXPECT_EQ(regions[31].hikey, 22);
        EXPECT_EQ(regions[32].hikey, 59);
        EXPECT_EQ(regions[33].hikey, 119);
        EXPECT_EQ(regions[34].hikey, 108);
        EXPECT_EQ(regions[35].hikey, default_hikey);
        EXPECT_EQ(regions[36].hikey, 47);
        EXPECT_EQ(regions[37].hikey, 95);
        EXPECT_EQ(regions[38].hikey, 120);
        EXPECT_EQ(regions[39].hikey, 13);
        EXPECT_EQ(regions[40].hikey, 49);
        EXPECT_EQ(regions[41].hikey, 2);
        EXPECT_EQ(regions[42].hikey, 14);
        EXPECT_EQ(regions[43].hikey, 111);
        EXPECT_EQ(regions[44].hikey, 123);
        EXPECT_EQ(regions[45].hikey, 111);
        EXPECT_EQ(regions[46].hikey, 16);
        EXPECT_EQ(regions[47].hikey, 5);
        EXPECT_EQ(regions[48].hikey, 53);
        EXPECT_EQ(regions[49].hikey, 125);
        EXPECT_EQ(regions[50].hikey, 4);
        EXPECT_EQ(regions[51].hikey, 53);
        EXPECT_EQ(regions[52].hikey, 18);
        EXPECT_EQ(regions[53].hikey, 114);
        EXPECT_EQ(regions[54].hikey, 126);
        EXPECT_EQ(regions[55].hikey, 127);
        EXPECT_EQ(regions[56].hikey, 8);
        EXPECT_EQ(regions[57].hikey, 56);
        EXPECT_EQ(regions[58].hikey, 104);
        EXPECT_EQ(regions[59].hikey, 18);
        EXPECT_EQ(regions[60].hikey, 104);
        EXPECT_EQ(regions[61].hikey, 116);
        EXPECT_EQ(regions[62].hikey, 57);
        EXPECT_EQ(regions[63].hikey, 10);
        EXPECT_EQ(regions[64].hikey, 22);
        EXPECT_EQ(regions[65].hikey, 22);
        EXPECT_EQ(regions[66].hikey, 118);
        EXPECT_EQ(regions[67].hikey, 11);
        EXPECT_EQ(regions[68].hikey, 107);
        EXPECT_EQ(regions[69].hikey, 60);
        EXPECT_EQ(regions[70].hikey, default_hikey);
        EXPECT_EQ(regions[71].hikey, default_hikey);
        EXPECT_EQ(regions[72].hikey, default_hikey);
        EXPECT_EQ(regions[73].hikey, default_hikey);
        EXPECT_EQ(regions[74].hikey, default_hikey);
        EXPECT_EQ(regions[75].hikey, default_hikey);
        EXPECT_EQ(regions[76].hikey, default_hikey);
        EXPECT_EQ(regions[77].hikey, default_hikey);
        EXPECT_EQ(regions[78].hikey, default_hikey);
        EXPECT_EQ(regions[79].hikey, default_hikey);
        EXPECT_EQ(regions[80].hikey, default_hikey);
        EXPECT_EQ(regions[81].hikey, default_hikey);
        EXPECT_EQ(regions[82].hikey, default_hikey);
        EXPECT_EQ(regions[83].hikey, default_hikey);
        EXPECT_EQ(regions[84].hikey, default_hikey);
        EXPECT_EQ(regions[85].hikey, default_hikey);
        EXPECT_EQ(regions[86].hikey, default_hikey);
        EXPECT_EQ(regions[87].hikey, default_hikey);
        EXPECT_EQ(regions[88].hikey, default_hikey);
        EXPECT_EQ(regions[89].hikey, default_hikey);
        EXPECT_EQ(regions[90].hikey, default_hikey);
        EXPECT_EQ(regions[91].hikey, default_hikey);
        EXPECT_EQ(regions[92].hikey, default_hikey);
        EXPECT_EQ(regions[93].hikey, default_hikey);
        EXPECT_EQ(regions[94].hikey, default_hikey);
        EXPECT_EQ(regions[95].hikey, default_hikey);
        EXPECT_EQ(regions[96].hikey, default_hikey);
        EXPECT_EQ(regions[97].hikey, default_hikey);
        EXPECT_EQ(regions[98].hikey, default_hikey);
        EXPECT_EQ(regions[99].hikey, default_hikey);
        EXPECT_EQ(regions[100].hikey, default_hikey);
        EXPECT_EQ(regions[101].hikey, default_hikey);
        EXPECT_EQ(regions[102].hikey, default_hikey);
        EXPECT_EQ(regions[103].hikey, default_hikey);
        EXPECT_EQ(regions[104].hikey, default_hikey);
        EXPECT_EQ(regions[105].hikey, default_hikey);
        EXPECT_EQ(regions[106].hikey, default_hikey);
        EXPECT_EQ(regions[107].hikey, 0);
        EXPECT_EQ(regions[108].hikey, default_hikey);
        EXPECT_EQ(regions[109].hikey, default_hikey);
        EXPECT_EQ(regions[110].hikey, default_hikey);
        EXPECT_EQ(regions[111].hikey, default_hikey);
        EXPECT_EQ(regions[112].hikey, default_hikey);
        EXPECT_EQ(regions[113].hikey, default_hikey);
        EXPECT_EQ(regions[114].hikey, default_hikey);
        EXPECT_EQ(regions[115].hikey, default_hikey);
        EXPECT_EQ(regions[116].hikey, default_hikey);
        EXPECT_EQ(regions[117].hikey, default_hikey);
        EXPECT_EQ(regions[118].hikey, default_hikey);
        EXPECT_EQ(regions[119].hikey, default_hikey);
        EXPECT_EQ(regions[120].hikey, default_hikey);
        EXPECT_EQ(regions[121].hikey, default_hikey);
        EXPECT_EQ(regions[122].hikey, default_hikey);
        EXPECT_EQ(regions[123].hikey, default_hikey);
        EXPECT_EQ(regions[124].hikey, default_hikey);
        EXPECT_EQ(regions[125].hikey, default_hikey);
        EXPECT_EQ(regions[126].hikey, default_hikey);
        EXPECT_EQ(regions[127].hikey, default_hikey);
        EXPECT_EQ(regions[128].hikey, default_hikey);
        EXPECT_EQ(regions[129].hikey, default_hikey);
        EXPECT_EQ(regions[130].hikey, default_hikey);
        EXPECT_EQ(regions[131].hikey, default_hikey);
        EXPECT_EQ(regions[132].hikey, default_hikey);
        EXPECT_EQ(regions[133].hikey, default_hikey);
        EXPECT_EQ(regions[134].hikey, default_hikey);
        EXPECT_EQ(regions[135].hikey, default_hikey);
        EXPECT_EQ(regions[136].hikey, default_hikey);
        EXPECT_EQ(regions[137].hikey, default_hikey);
        EXPECT_EQ(regions[138].hikey, default_hikey);
        EXPECT_EQ(regions[139].hikey, default_hikey);
        EXPECT_EQ(regions[140].hikey, default_hikey);
        EXPECT_EQ(regions[141].hikey, default_hikey);
        EXPECT_EQ(regions[142].hikey, default_hikey);
        EXPECT_EQ(regions[143].hikey, default_hikey);
        EXPECT_EQ(regions[144].hikey, default_hikey);
        EXPECT_EQ(regions[145].hikey, default_hikey);
        EXPECT_EQ(regions[146].hikey, default_hikey);
        EXPECT_EQ(regions[147].hikey, default_hikey);
        EXPECT_EQ(regions[148].hikey, 0);
        EXPECT_EQ(regions[149].hikey, default_hikey);
        EXPECT_EQ(regions[150].hikey, default_hikey);
        EXPECT_EQ(regions[151].hikey, default_hikey);
        EXPECT_EQ(regions[152].hikey, default_hikey);
        EXPECT_EQ(regions[153].hikey, default_hikey);
        EXPECT_EQ(regions[154].hikey, default_hikey);
        EXPECT_EQ(regions[155].hikey, default_hikey);
        EXPECT_EQ(regions[156].hikey, default_hikey);
        EXPECT_EQ(regions[157].hikey, default_hikey);
        EXPECT_EQ(regions[158].hikey, default_hikey);
        EXPECT_EQ(regions[159].hikey, default_hikey);
        EXPECT_EQ(regions[160].hikey, default_hikey);
        EXPECT_EQ(regions[161].hikey, default_hikey);
        EXPECT_EQ(regions[162].hikey, default_hikey);
    }
}

TEST_F(SfzTest, key_notename) {
    create_file("testdata/SFZSink/key_notename.sfz",
                "<region> key=Cb8\n"
                "<region> key=C-1\n"
                "<region> key=C8\n"
                "<region> key=C#0\n"
                "<region> key=C#3\n"
                "<region> key=Db3\n"
                "<region> key=Db9\n"
                "<region> key=D-1\n"
                "<region> key=D8\n"
                "<region> key=D#0\n"
                "<region> key=Eb3\n"
                "<region> key=Eb8\n"
                "<region> key=E-1\n"
                "<region> key=E#0\n"
                "<region> key=E#9\n"
                "<region> key=Fb0\n"
                "<region> key=Fb3\n"
                "<region> key=F8\n"
                "<region> key=F#-1\n"
                "<region> key=F#9\n"
                "<region> key=Gb8\n"
                "<region> key=Gb9\n"
                "<region> key=G-1\n"
                "<region> key=G0\n"
                "<region> key=G#3\n"
                "<region> key=Ab0\n"
                "<region> key=A3\n"
                "<region> key=A#-1\n"
                "<region> key=A#7\n"
                "<region> key=A#8\n"
                "<region> key=Bb-1\n"
                "<region> key=Bb0\n"
                "<region> key=B3\n"
                "<region> key=B8\n"
                "<region> key=B#7\n"
                "<region> key=cb-1\n"
                "<region> key=cb3\n"
                "<region> key=cb7\n"
                "<region> key=c9\n"
                "<region> key=c#0\n"
                "<region> key=db3\n"
                "<region> key=d-1\n"
                "<region> key=d0\n"
                "<region> key=d#8\n"
                "<region> key=d#9\n"
                "<region> key=eb8\n"
                "<region> key=e0\n"
                "<region> key=e#-1\n"
                "<region> key=e#3\n"
                "<region> key=e#9\n"
                "<region> key=fb-1\n"
                "<region> key=f3\n"
                "<region> key=f#0\n"
                "<region> key=f#8\n"
                "<region> key=f#9\n"
                "<region> key=g9\n"
                "<region> key=g#-1\n"
                "<region> key=g#3\n"
                "<region> key=g#7\n"
                "<region> key=gb0\n"
                "<region> key=ab7\n"
                "<region> key=ab8\n"
                "<region> key=a3\n"
                "<region> key=a#-1\n"
                "<region> key=a#0\n"
                "<region> key=bb0\n"
                "<region> key=bb8\n"
                "<region> key=b-1\n"
                "<region> key=b7\n"
                "<region> key=b#3\n"
                "<region> key=C##\n"
                "<region> key=C#-2\n"
                "<region> key=C#b\n"
                "<region> key=C-100\n"
                "<region> key=C10\n"
                "<region> key=CbZZ\n"
                "<region> key=D#\n"
                "<region> key=D#-100\n"
                "<region> key=D#10\n"
                "<region> key=D#ZZ\n"
                "<region> key=Db\n"
                "<region> key=Db-2\n"
                "<region> key=E#-100\n"
                "<region> key=E#ZZ\n"
                "<region> key=E#b\n"
                "<region> key=E-2\n"
                "<region> key=E10\n"
                "<region> key=Eb#\n"
                "<region> key=F##\n"
                "<region> key=F#-100\n"
                "<region> key=F#-2\n"
                "<region> key=FZZ\n"
                "<region> key=Fb10\n"
                "<region> key=Fbb\n"
                "<region> key=G##\n"
                "<region> key=G#-100\n"
                "<region> key=G#ZZ\n"
                "<region> key=G10\n"
                "<region> key=Gb\n"
                "<region> key=Gb-2\n"
                "<region> key=A#\n"
                "<region> key=A#10\n"
                "<region> key=AZZ\n"
                "<region> key=Ab\n"
                "<region> key=Ab-100\n"
                "<region> key=Ab-2\n"
                "<region> key=B#\n"
                "<region> key=B#-2\n"
                "<region> key=B-100\n"
                "<region> key=Bb\n"
                "<region> key=Bb10\n"
                "<region> key=BbZZ\n"
                "<region> key=c#\n"
                "<region> key=c#10\n"
                "<region> key=c#b\n"
                "<region> key=c-2\n"
                "<region> key=cb-100\n"
                "<region> key=cbZZ\n"
                "<region> key=d##\n"
                "<region> key=d-100\n"
                "<region> key=d-2\n"
                "<region> key=d10\n"
                "<region> key=dbZZ\n"
                "<region> key=dbb\n"
                "<region> key=e#\n"
                "<region> key=e#-2\n"
                "<region> key=e#10\n"
                "<region> key=eZZ\n"
                "<region> key=eb\n"
                "<region> key=eb-100\n"
                "<region> key=f#\n"
                "<region> key=f#ZZ\n"
                "<region> key=f-100\n"
                "<region> key=fb-2\n"
                "<region> key=fb10\n"
                "<region> key=fbb\n"
                "<region> key=g#ZZ\n"
                "<region> key=g10\n"
                "<region> key=gb\n"
                "<region> key=gb#\n"
                "<region> key=gb-100\n"
                "<region> key=gb-2\n"
                "<region> key=a#ZZ\n"
                "<region> key=a-2\n"
                "<region> key=a10\n"
                "<region> key=ab#\n"
                "<region> key=ab-100\n"
                "<region> key=abb\n"
                "<region> key=b#-2\n"
                "<region> key=b#ZZ\n"
                "<region> key=b10\n"
                "<region> key=bb#\n"
                "<region> key=bb-100\n"
                "<region> key=bbb\n"
                "<region> key=Z3\n"
                "<region> key=Zb3\n"
                "<region> key=Z#3\n"
                "<region> key=10#3\n"
                "<region> key=10b3\n"
                "<region> key==C3\n"
                "<region> key=Cz3\n"
                "<region> key=C♭3\n"
                "<region> key=C=3\n"
                "");
    SFZSink sfz_test = SFZSink("testdata/SFZSink/key_notename.sfz");
    regions = getSfzData(sfz_test);

    EXPECT_EQ(regions.size(), 163);
    if (regions.size() >= 163) {
        const uint32_t default_lokey = NOTE_NUMBER_MIN, default_hikey = NOTE_NUMBER_MAX;
        EXPECT_EQ(regions[0].lokey, 107);
        EXPECT_EQ(regions[1].lokey, 0);
        EXPECT_EQ(regions[2].lokey, 108);
        EXPECT_EQ(regions[3].lokey, 13);
        EXPECT_EQ(regions[4].lokey, 49);
        EXPECT_EQ(regions[5].lokey, 49);
        EXPECT_EQ(regions[6].lokey, 121);
        EXPECT_EQ(regions[7].lokey, 2);
        EXPECT_EQ(regions[8].lokey, 110);
        EXPECT_EQ(regions[9].lokey, 15);
        EXPECT_EQ(regions[10].lokey, 51);
        EXPECT_EQ(regions[11].lokey, 111);
        EXPECT_EQ(regions[12].lokey, 4);
        EXPECT_EQ(regions[13].lokey, 17);
        EXPECT_EQ(regions[14].lokey, 125);
        EXPECT_EQ(regions[15].lokey, 16);
        EXPECT_EQ(regions[16].lokey, 52);
        EXPECT_EQ(regions[17].lokey, 113);
        EXPECT_EQ(regions[18].lokey, 6);
        EXPECT_EQ(regions[19].lokey, 126);
        EXPECT_EQ(regions[20].lokey, 114);
        EXPECT_EQ(regions[21].lokey, 126);
        EXPECT_EQ(regions[22].lokey, 7);
        EXPECT_EQ(regions[23].lokey, 19);
        EXPECT_EQ(regions[24].lokey, 56);
        EXPECT_EQ(regions[25].lokey, 20);
        EXPECT_EQ(regions[26].lokey, 57);
        EXPECT_EQ(regions[27].lokey, 10);
        EXPECT_EQ(regions[28].lokey, 106);
        EXPECT_EQ(regions[29].lokey, 118);
        EXPECT_EQ(regions[30].lokey, 10);
        EXPECT_EQ(regions[31].lokey, 22);
        EXPECT_EQ(regions[32].lokey, 59);
        EXPECT_EQ(regions[33].lokey, 119);
        EXPECT_EQ(regions[34].lokey, 108);
        EXPECT_EQ(regions[35].lokey, default_lokey);
        EXPECT_EQ(regions[36].lokey, 47);
        EXPECT_EQ(regions[37].lokey, 95);
        EXPECT_EQ(regions[38].lokey, 120);
        EXPECT_EQ(regions[39].lokey, 13);
        EXPECT_EQ(regions[40].lokey, 49);
        EXPECT_EQ(regions[41].lokey, 2);
        EXPECT_EQ(regions[42].lokey, 14);
        EXPECT_EQ(regions[43].lokey, 111);
        EXPECT_EQ(regions[44].lokey, 123);
        EXPECT_EQ(regions[45].lokey, 111);
        EXPECT_EQ(regions[46].lokey, 16);
        EXPECT_EQ(regions[47].lokey, 5);
        EXPECT_EQ(regions[48].lokey, 53);
        EXPECT_EQ(regions[49].lokey, 125);
        EXPECT_EQ(regions[50].lokey, 4);
        EXPECT_EQ(regions[51].lokey, 53);
        EXPECT_EQ(regions[52].lokey, 18);
        EXPECT_EQ(regions[53].lokey, 114);
        EXPECT_EQ(regions[54].lokey, 126);
        EXPECT_EQ(regions[55].lokey, 127);
        EXPECT_EQ(regions[56].lokey, 8);
        EXPECT_EQ(regions[57].lokey, 56);
        EXPECT_EQ(regions[58].lokey, 104);
        EXPECT_EQ(regions[59].lokey, 18);
        EXPECT_EQ(regions[60].lokey, 104);
        EXPECT_EQ(regions[61].lokey, 116);
        EXPECT_EQ(regions[62].lokey, 57);
        EXPECT_EQ(regions[63].lokey, 10);
        EXPECT_EQ(regions[64].lokey, 22);
        EXPECT_EQ(regions[65].lokey, 22);
        EXPECT_EQ(regions[66].lokey, 118);
        EXPECT_EQ(regions[67].lokey, 11);
        EXPECT_EQ(regions[68].lokey, 107);
        EXPECT_EQ(regions[69].lokey, 60);
        EXPECT_EQ(regions[70].lokey, default_lokey);
        EXPECT_EQ(regions[71].lokey, default_lokey);
        EXPECT_EQ(regions[72].lokey, default_lokey);
        EXPECT_EQ(regions[73].lokey, default_lokey);
        EXPECT_EQ(regions[74].lokey, default_lokey);
        EXPECT_EQ(regions[75].lokey, default_lokey);
        EXPECT_EQ(regions[76].lokey, default_lokey);
        EXPECT_EQ(regions[77].lokey, default_lokey);
        EXPECT_EQ(regions[78].lokey, default_lokey);
        EXPECT_EQ(regions[79].lokey, default_lokey);
        EXPECT_EQ(regions[80].lokey, default_lokey);
        EXPECT_EQ(regions[81].lokey, default_lokey);
        EXPECT_EQ(regions[82].lokey, default_lokey);
        EXPECT_EQ(regions[83].lokey, default_lokey);
        EXPECT_EQ(regions[84].lokey, default_lokey);
        EXPECT_EQ(regions[85].lokey, default_lokey);
        EXPECT_EQ(regions[86].lokey, default_lokey);
        EXPECT_EQ(regions[87].lokey, default_lokey);
        EXPECT_EQ(regions[88].lokey, default_lokey);
        EXPECT_EQ(regions[89].lokey, default_lokey);
        EXPECT_EQ(regions[90].lokey, default_lokey);
        EXPECT_EQ(regions[91].lokey, default_lokey);
        EXPECT_EQ(regions[92].lokey, default_lokey);
        EXPECT_EQ(regions[93].lokey, default_lokey);
        EXPECT_EQ(regions[94].lokey, default_lokey);
        EXPECT_EQ(regions[95].lokey, default_lokey);
        EXPECT_EQ(regions[96].lokey, default_lokey);
        EXPECT_EQ(regions[97].lokey, default_lokey);
        EXPECT_EQ(regions[98].lokey, default_lokey);
        EXPECT_EQ(regions[99].lokey, default_lokey);
        EXPECT_EQ(regions[100].lokey, default_lokey);
        EXPECT_EQ(regions[101].lokey, default_lokey);
        EXPECT_EQ(regions[102].lokey, default_lokey);
        EXPECT_EQ(regions[103].lokey, default_lokey);
        EXPECT_EQ(regions[104].lokey, default_lokey);
        EXPECT_EQ(regions[105].lokey, default_lokey);
        EXPECT_EQ(regions[106].lokey, default_lokey);
        EXPECT_EQ(regions[107].lokey, default_lokey);
        EXPECT_EQ(regions[108].lokey, default_lokey);
        EXPECT_EQ(regions[109].lokey, default_lokey);
        EXPECT_EQ(regions[110].lokey, default_lokey);
        EXPECT_EQ(regions[111].lokey, default_lokey);
        EXPECT_EQ(regions[112].lokey, default_lokey);
        EXPECT_EQ(regions[113].lokey, default_lokey);
        EXPECT_EQ(regions[114].lokey, default_lokey);
        EXPECT_EQ(regions[115].lokey, default_lokey);
        EXPECT_EQ(regions[116].lokey, default_lokey);
        EXPECT_EQ(regions[117].lokey, default_lokey);
        EXPECT_EQ(regions[118].lokey, default_lokey);
        EXPECT_EQ(regions[119].lokey, default_lokey);
        EXPECT_EQ(regions[120].lokey, default_lokey);
        EXPECT_EQ(regions[121].lokey, default_lokey);
        EXPECT_EQ(regions[122].lokey, default_lokey);
        EXPECT_EQ(regions[123].lokey, default_lokey);
        EXPECT_EQ(regions[124].lokey, default_lokey);
        EXPECT_EQ(regions[125].lokey, default_lokey);
        EXPECT_EQ(regions[126].lokey, default_lokey);
        EXPECT_EQ(regions[127].lokey, default_lokey);
        EXPECT_EQ(regions[128].lokey, default_lokey);
        EXPECT_EQ(regions[129].lokey, default_lokey);
        EXPECT_EQ(regions[130].lokey, default_lokey);
        EXPECT_EQ(regions[131].lokey, default_lokey);
        EXPECT_EQ(regions[132].lokey, default_lokey);
        EXPECT_EQ(regions[133].lokey, default_lokey);
        EXPECT_EQ(regions[134].lokey, default_lokey);
        EXPECT_EQ(regions[135].lokey, default_lokey);
        EXPECT_EQ(regions[136].lokey, default_lokey);
        EXPECT_EQ(regions[137].lokey, default_lokey);
        EXPECT_EQ(regions[138].lokey, default_lokey);
        EXPECT_EQ(regions[139].lokey, default_lokey);
        EXPECT_EQ(regions[140].lokey, default_lokey);
        EXPECT_EQ(regions[141].lokey, default_lokey);
        EXPECT_EQ(regions[142].lokey, default_lokey);
        EXPECT_EQ(regions[143].lokey, default_lokey);
        EXPECT_EQ(regions[144].lokey, default_lokey);
        EXPECT_EQ(regions[145].lokey, default_lokey);
        EXPECT_EQ(regions[146].lokey, default_lokey);
        EXPECT_EQ(regions[147].lokey, default_lokey);
        EXPECT_EQ(regions[148].lokey, default_lokey);
        EXPECT_EQ(regions[149].lokey, default_lokey);
        EXPECT_EQ(regions[150].lokey, default_lokey);
        EXPECT_EQ(regions[151].lokey, default_lokey);
        EXPECT_EQ(regions[152].lokey, default_lokey);
        EXPECT_EQ(regions[153].lokey, default_lokey);
        EXPECT_EQ(regions[154].lokey, default_lokey);
        EXPECT_EQ(regions[155].lokey, default_lokey);
        EXPECT_EQ(regions[156].lokey, default_lokey);
        EXPECT_EQ(regions[157].lokey, default_lokey);
        EXPECT_EQ(regions[158].lokey, default_lokey);
        EXPECT_EQ(regions[159].lokey, default_lokey);
        EXPECT_EQ(regions[160].lokey, default_lokey);
        EXPECT_EQ(regions[161].lokey, default_lokey);
        EXPECT_EQ(regions[162].lokey, default_lokey);

        EXPECT_EQ(regions[0].hikey, 107);
        EXPECT_EQ(regions[1].hikey, 0);
        EXPECT_EQ(regions[2].hikey, 108);
        EXPECT_EQ(regions[3].hikey, 13);
        EXPECT_EQ(regions[4].hikey, 49);
        EXPECT_EQ(regions[5].hikey, 49);
        EXPECT_EQ(regions[6].hikey, 121);
        EXPECT_EQ(regions[7].hikey, 2);
        EXPECT_EQ(regions[8].hikey, 110);
        EXPECT_EQ(regions[9].hikey, 15);
        EXPECT_EQ(regions[10].hikey, 51);
        EXPECT_EQ(regions[11].hikey, 111);
        EXPECT_EQ(regions[12].hikey, 4);
        EXPECT_EQ(regions[13].hikey, 17);
        EXPECT_EQ(regions[14].hikey, 125);
        EXPECT_EQ(regions[15].hikey, 16);
        EXPECT_EQ(regions[16].hikey, 52);
        EXPECT_EQ(regions[17].hikey, 113);
        EXPECT_EQ(regions[18].hikey, 6);
        EXPECT_EQ(regions[19].hikey, 126);
        EXPECT_EQ(regions[20].hikey, 114);
        EXPECT_EQ(regions[21].hikey, 126);
        EXPECT_EQ(regions[22].hikey, 7);
        EXPECT_EQ(regions[23].hikey, 19);
        EXPECT_EQ(regions[24].hikey, 56);
        EXPECT_EQ(regions[25].hikey, 20);
        EXPECT_EQ(regions[26].hikey, 57);
        EXPECT_EQ(regions[27].hikey, 10);
        EXPECT_EQ(regions[28].hikey, 106);
        EXPECT_EQ(regions[29].hikey, 118);
        EXPECT_EQ(regions[30].hikey, 10);
        EXPECT_EQ(regions[31].hikey, 22);
        EXPECT_EQ(regions[32].hikey, 59);
        EXPECT_EQ(regions[33].hikey, 119);
        EXPECT_EQ(regions[34].hikey, 108);
        EXPECT_EQ(regions[35].hikey, default_hikey);
        EXPECT_EQ(regions[36].hikey, 47);
        EXPECT_EQ(regions[37].hikey, 95);
        EXPECT_EQ(regions[38].hikey, 120);
        EXPECT_EQ(regions[39].hikey, 13);
        EXPECT_EQ(regions[40].hikey, 49);
        EXPECT_EQ(regions[41].hikey, 2);
        EXPECT_EQ(regions[42].hikey, 14);
        EXPECT_EQ(regions[43].hikey, 111);
        EXPECT_EQ(regions[44].hikey, 123);
        EXPECT_EQ(regions[45].hikey, 111);
        EXPECT_EQ(regions[46].hikey, 16);
        EXPECT_EQ(regions[47].hikey, 5);
        EXPECT_EQ(regions[48].hikey, 53);
        EXPECT_EQ(regions[49].hikey, 125);
        EXPECT_EQ(regions[50].hikey, 4);
        EXPECT_EQ(regions[51].hikey, 53);
        EXPECT_EQ(regions[52].hikey, 18);
        EXPECT_EQ(regions[53].hikey, 114);
        EXPECT_EQ(regions[54].hikey, 126);
        EXPECT_EQ(regions[55].hikey, 127);
        EXPECT_EQ(regions[56].hikey, 8);
        EXPECT_EQ(regions[57].hikey, 56);
        EXPECT_EQ(regions[58].hikey, 104);
        EXPECT_EQ(regions[59].hikey, 18);
        EXPECT_EQ(regions[60].hikey, 104);
        EXPECT_EQ(regions[61].hikey, 116);
        EXPECT_EQ(regions[62].hikey, 57);
        EXPECT_EQ(regions[63].hikey, 10);
        EXPECT_EQ(regions[64].hikey, 22);
        EXPECT_EQ(regions[65].hikey, 22);
        EXPECT_EQ(regions[66].hikey, 118);
        EXPECT_EQ(regions[67].hikey, 11);
        EXPECT_EQ(regions[68].hikey, 107);
        EXPECT_EQ(regions[69].hikey, 60);
        EXPECT_EQ(regions[70].hikey, default_hikey);
        EXPECT_EQ(regions[71].hikey, default_hikey);
        EXPECT_EQ(regions[72].hikey, default_hikey);
        EXPECT_EQ(regions[73].hikey, default_hikey);
        EXPECT_EQ(regions[74].hikey, default_hikey);
        EXPECT_EQ(regions[75].hikey, default_hikey);
        EXPECT_EQ(regions[76].hikey, default_hikey);
        EXPECT_EQ(regions[77].hikey, default_hikey);
        EXPECT_EQ(regions[78].hikey, default_hikey);
        EXPECT_EQ(regions[79].hikey, default_hikey);
        EXPECT_EQ(regions[80].hikey, default_hikey);
        EXPECT_EQ(regions[81].hikey, default_hikey);
        EXPECT_EQ(regions[82].hikey, default_hikey);
        EXPECT_EQ(regions[83].hikey, default_hikey);
        EXPECT_EQ(regions[84].hikey, default_hikey);
        EXPECT_EQ(regions[85].hikey, default_hikey);
        EXPECT_EQ(regions[86].hikey, default_hikey);
        EXPECT_EQ(regions[87].hikey, default_hikey);
        EXPECT_EQ(regions[88].hikey, default_hikey);
        EXPECT_EQ(regions[89].hikey, default_hikey);
        EXPECT_EQ(regions[90].hikey, default_hikey);
        EXPECT_EQ(regions[91].hikey, default_hikey);
        EXPECT_EQ(regions[92].hikey, default_hikey);
        EXPECT_EQ(regions[93].hikey, default_hikey);
        EXPECT_EQ(regions[94].hikey, default_hikey);
        EXPECT_EQ(regions[95].hikey, default_hikey);
        EXPECT_EQ(regions[96].hikey, default_hikey);
        EXPECT_EQ(regions[97].hikey, default_hikey);
        EXPECT_EQ(regions[98].hikey, default_hikey);
        EXPECT_EQ(regions[99].hikey, default_hikey);
        EXPECT_EQ(regions[100].hikey, default_hikey);
        EXPECT_EQ(regions[101].hikey, default_hikey);
        EXPECT_EQ(regions[102].hikey, default_hikey);
        EXPECT_EQ(regions[103].hikey, default_hikey);
        EXPECT_EQ(regions[104].hikey, default_hikey);
        EXPECT_EQ(regions[105].hikey, default_hikey);
        EXPECT_EQ(regions[106].hikey, default_hikey);
        EXPECT_EQ(regions[107].hikey, 0);
        EXPECT_EQ(regions[108].hikey, default_hikey);
        EXPECT_EQ(regions[109].hikey, default_hikey);
        EXPECT_EQ(regions[110].hikey, default_hikey);
        EXPECT_EQ(regions[111].hikey, default_hikey);
        EXPECT_EQ(regions[112].hikey, default_hikey);
        EXPECT_EQ(regions[113].hikey, default_hikey);
        EXPECT_EQ(regions[114].hikey, default_hikey);
        EXPECT_EQ(regions[115].hikey, default_hikey);
        EXPECT_EQ(regions[116].hikey, default_hikey);
        EXPECT_EQ(regions[117].hikey, default_hikey);
        EXPECT_EQ(regions[118].hikey, default_hikey);
        EXPECT_EQ(regions[119].hikey, default_hikey);
        EXPECT_EQ(regions[120].hikey, default_hikey);
        EXPECT_EQ(regions[121].hikey, default_hikey);
        EXPECT_EQ(regions[122].hikey, default_hikey);
        EXPECT_EQ(regions[123].hikey, default_hikey);
        EXPECT_EQ(regions[124].hikey, default_hikey);
        EXPECT_EQ(regions[125].hikey, default_hikey);
        EXPECT_EQ(regions[126].hikey, default_hikey);
        EXPECT_EQ(regions[127].hikey, default_hikey);
        EXPECT_EQ(regions[128].hikey, default_hikey);
        EXPECT_EQ(regions[129].hikey, default_hikey);
        EXPECT_EQ(regions[130].hikey, default_hikey);
        EXPECT_EQ(regions[131].hikey, default_hikey);
        EXPECT_EQ(regions[132].hikey, default_hikey);
        EXPECT_EQ(regions[133].hikey, default_hikey);
        EXPECT_EQ(regions[134].hikey, default_hikey);
        EXPECT_EQ(regions[135].hikey, default_hikey);
        EXPECT_EQ(regions[136].hikey, default_hikey);
        EXPECT_EQ(regions[137].hikey, default_hikey);
        EXPECT_EQ(regions[138].hikey, default_hikey);
        EXPECT_EQ(regions[139].hikey, default_hikey);
        EXPECT_EQ(regions[140].hikey, default_hikey);
        EXPECT_EQ(regions[141].hikey, default_hikey);
        EXPECT_EQ(regions[142].hikey, default_hikey);
        EXPECT_EQ(regions[143].hikey, default_hikey);
        EXPECT_EQ(regions[144].hikey, default_hikey);
        EXPECT_EQ(regions[145].hikey, default_hikey);
        EXPECT_EQ(regions[146].hikey, default_hikey);
        EXPECT_EQ(regions[147].hikey, default_hikey);
        EXPECT_EQ(regions[148].hikey, 0);
        EXPECT_EQ(regions[149].hikey, default_hikey);
        EXPECT_EQ(regions[150].hikey, default_hikey);
        EXPECT_EQ(regions[151].hikey, default_hikey);
        EXPECT_EQ(regions[152].hikey, default_hikey);
        EXPECT_EQ(regions[153].hikey, default_hikey);
        EXPECT_EQ(regions[154].hikey, default_hikey);
        EXPECT_EQ(regions[155].hikey, default_hikey);
        EXPECT_EQ(regions[156].hikey, default_hikey);
        EXPECT_EQ(regions[157].hikey, default_hikey);
        EXPECT_EQ(regions[158].hikey, default_hikey);
        EXPECT_EQ(regions[159].hikey, default_hikey);
        EXPECT_EQ(regions[160].hikey, default_hikey);
        EXPECT_EQ(regions[161].hikey, default_hikey);
        EXPECT_EQ(regions[162].hikey, default_hikey);
    }
}
