/*
 * SPDX-License-Identifier: (Apache-2.0 OR LGPL-2.1-or-later)
 *
 * Copyright 2022 Sony Semiconductor Solutions Corporation
 */

#ifndef MIDI_UTIL_H_

enum MidiMessageType {
    MIDI_MSG_NOTE_OFF = 0x80,
    MIDI_MSG_NOTE_ON = 0x90,
    MIDI_MSG_POLYPHONIC_KEY_PRESSURE = 0xA0,
    MIDI_MSG_CONTROL_CHANGE = 0xB0,
    MIDI_MSG_PROGRAM_CHANGE = 0xC0,
    MIDI_MSG_CHANNEL_PRESSURE = 0xD0,
    MIDI_MSG_PITCH_BEND_CHANGE = 0xE0,
    MIDI_MSG_SYS_EX_EVENT = 0xF0,
    MIDI_MSG_SONG_POSITION_POINTER = 0xF2,
    MIDI_MSG_SONG_SELECT = 0xF3,
    MIDI_MSG_END_OF_EXCLUSIVE = 0xF7,
    MIDI_MSG_START = 0xFA,
    MIDI_MSG_CONTINUE = 0xFB,
    MIDI_MSG_STOP = 0xFC,
    MIDI_MSG_META_EVENT = 0xFF
};

enum MidiMessageLength {
    MIDI_MSGLEN_NOTE_OFF = 3,
    MIDI_MSGLEN_NOTE_ON = 3,
    MIDI_MSGLEN_POLYPHONIC_KEY_PRESSURE = 3,
    MIDI_MSGLEN_CONTROL_CHANGE = 3,
    MIDI_MSGLEN_PROGRAM_CHANGE = 2,
    MIDI_MSGLEN_CHANNEL_PRESSURE = 2,
    MIDI_MSGLEN_PITCH_BEND_CHANGE = 3,
    MIDI_MSGLEN_SYS_EX_EVENT = 2,
    MIDI_MSGLEN_SONG_POSITION_POINTER = 4,
    MIDI_MSGLEN_SONG_SELECT = 2,
    MIDI_MSGLEN_END_OF_EXCLUSIVE = 2,
    MIDI_MSGLEN_START = 1,
    MIDI_MSGLEN_CONTINUE = 1,
    MIDI_MSGLEN_STOP = 1,
    MIDI_MSGLEN_META_EVENT = 3
};

enum MidiMetaEventType {
    MIDI_META_SEQUENCE_NUBMER = 0x00,
    MIDI_META_TEXT_EVENT = 0x01,
    MIDI_META_COPYRIGHT_NOTICE = 0x02,
    MIDI_META_TRACK_NAME = 0x03,
    MIDI_META_INSTRUMENT_NAME = 0x04,
    MIDI_META_LYRIC = 0x05,
    MIDI_META_MARKER = 0x06,
    MIDI_META_CUE_POINT = 0x07,
    MIDI_META_PROGRAM_NAME = 0x08,
    MIDI_META_DEVICE_NAME = 0x09,
    MIDI_META_MIDI_CHANNEL_PREFIX = 0x20,
    MIDI_META_PORT = 0x21,
    MIDI_META_END_OF_TRACK = 0x2F,
    MIDI_META_SET_TEMPO = 0x51,
    MIDI_META_SMPTE_OFFSET = 0x54,
    MIDI_META_TIME_SIGNATURE = 0x58,
    MIDI_META_KEY_SIGNATURE = 0x59,
    MIDI_META_SEQUENCER_SPECIFIC = 0x7F
};

enum MidiMetaEventLength {
    MIDI_METALEN_SEQUENCE_NUBMER = 2,
    MIDI_METALEN_TEXT_EVENT = 0,
    MIDI_METALEN_COPYRIGHT_NOTICE = 0,
    MIDI_METALEN_TRACK_NAME = 0,
    MIDI_METALEN_INSTRUMENT_NAME = 0,
    MIDI_METALEN_LYRIC = 0,
    MIDI_METALEN_MARKER = 0,
    MIDI_METALEN_CUE_POINT = 0,
    MIDI_METALEN_MIDI_CHANNEL_PREFIX = 1,
    MIDI_METALEN_END_OF_TRACK = 0,
    MIDI_METALEN_SET_TEMPO = 3,
    MIDI_METALEN_SMPTE_OFFSET = 5,
    MIDI_METALEN_TIME_SIGNATURE = 4,
    MIDI_METALEN_KEY_SIGNATURE = 2,
    MIDI_METALEN_SEQUENCER_SPECIFIC = 0
};

#endif  // MIDI_UTIL_H_
